# Generated by Erlang.mk. Edit at your own risk!

src/p06.erl:: src/p05.erl; @touch $@
src/p08.erl:: src/p05.erl; @touch $@
src/p09.erl:: src/p05.erl; @touch $@
src/p10.erl:: src/p05.erl; @touch $@
src/p11.erl:: src/p05.erl; @touch $@
src/p12.erl:: src/p05.erl; @touch $@
src/p13.erl:: src/p05.erl; @touch $@
src/p14.erl:: src/p05.erl; @touch $@
src/p15.erl:: src/p05.erl; @touch $@

COMPILE_FIRST += p05
